version: '3'
services:
  mysqldb:
    platform: linux/x86_64 # for Mac M1
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
